Cerebellum-Network/cere-ddc-sdk-js

CHANGELOG.md
packages/smart-contract/src/SmartContract.ts
tests/SmartContract.spec.ts

Use dynamic value of CERE token decimals from blockchain properties instead of hardcoding it to equal `10`

Get $CERE decimals value from blockchain properties

---

packages/smart-contract/src/SmartContract.ts
packages/smart-contract/src/SmartContractBase.ts
tests/SmartContract.spec.ts

Added `batch` method which allows to batch smart contract calls into a single transaction.
The method accepts a single parameter - `builder`. It is a synchronous function in which all SC calls will be batched.
```ts
await contract.batch(() => {
contract.clusterSetNodeStatus(clusterId, storageNodeKey, NodeStatusInCluster.ACTIVE),
contract.clusterSetCdnNodeStatus(clusterId, cdnNodeKey, NodeStatusInCluster.ACTIVE),
});
```
The limitation is that only the calls which were called during the builder synchronise execution will be added to the batch.
The builder can optionally return an array of promises, which will be resolved with `Promise.all` under the hood:
```ts
const [nodeKey, cdnNodeKey] = await contract.batch(() => [
contract.nodeCreate(...),
contract.cdnNodeCreate(...)
]);
```

Smart Contract calls batch

---

CHANGELOG.md
packages/smart-contract/src/SmartContract.ts
packages/smart-contract/src/options/SmartContractOptions.ts
tests/SmartContract.spec.ts

Add bucket availability method to Smart Contract module

---

packages/content-addressable-storage/src/ContentAddressableStorage.ts
packages/content-addressable-storage/src/collectionPoint/CollectionPoint.ts

Instead of requesting search result with content we always use `skipData` option and read found pieces data using `read` method

Read found pieces content on client side

---

lerna.json
package-lock.json
packages/content-addressable-storage/package.json
packages/content-addressable-storage/src/ContentAddressableStorage.ts
packages/content-addressable-storage/src/collectionPoint/CollectionPoint.ts
packages/core/package.json
packages/ddc-client/package.json
packages/file-storage/package.json
packages/key-value-storage/package.json
packages/proto/package.json
packages/smart-contract/package.json

Calculate `bytesProcessed`  using the following rules:
- Read request: response body length
- Store request: request body length
Previously only piece data size was used for both cases

Calculate bytes of full read and store request body

---

packages/smart-contract/src/SmartContract.ts
packages/smart-contract/src/types/contractTypes.ts
tests/SmartContract.spec.ts

Change permission type from `enum` to `union` to emulate `Rust` enum.

Smart Contract hasPermission method fix

---

packages/ddc/protos/cns_api.proto
packages/ddc/protos/dag_api.proto
packages/ddc/protos/file_api.proto
packages/ddc/src/CnsApi/CnsApi.ts
packages/ddc/src/DagNode.ts
packages/ddc/src/StorageNode.ts
packages/ddc/src/grpc/cns_api.ts
packages/ddc/src/grpc/dag_api.ts
packages/ddc/src/grpc/file_api.ts
packages/ddc/src/index.ts
tests/v2/DdcApis.spec.ts

These API changes suported
- CIDs are always of `bytes` type (`Uint8Array`)
- Bucket IDs are always of `uint64` type (`number`)

Support latest storage node API types changes

---

package-lock.json
packages/core/package.json
packages/ddc-client/README.md
packages/ddc-client/package.json
packages/ddc-client/src/DdcClient.ts
packages/ddc-client/src/index.ts
packages/ddc-client/src/presets.ts
packages/file-storage/README.md
tests/v2/DdcClient.spec.ts

Add DDC Client configuration presets:
- DEVNET
- TESTNET
- MAINNET
So we could hide temporary storage nodes hardcoded list from the SDK users.
Also changed the order of parameters in `DdcClient.create` to make the configuration default to TESTNET (braking but should be easy to fix)

Add configuration presets

---

tests/setup/environment/ddc.ts
tests/setup/environment/docker-compose.ddc.yml
tests/v2/DdcClient.spec.ts

- Set `TEST_ENABLED=true` flag to storage nodes to get proper peers  configuration
- Disabled CDN nodes and related services in the test env since they are not used for now

Add test enabled flag to storage nodes

---

.github/workflows/publish.yaml
.github/workflows/tests.yaml
package.json
packages/ddc-client/src/DdcClient.ts
packages/ddc-client/src/index.ts
packages/ddc/package.json
packages/ddc/protos/cns_api.proto
packages/ddc/protos/dag_api.proto
packages/ddc/protos/file_api.proto
packages/ddc/src/StorageNode.ts
packages/ddc/src/grpc/cns_api.ts
packages/ddc/src/grpc/dag_api.ts
packages/ddc/src/grpc/file_api.ts
packages/ddc/src/presets.ts
packages/file-storage/src/FileStorage.ts
tests/specs/DdcApis.spec.ts
tests/specs/DdcClient.spec.ts
tests/specs/FileStorage.spec.ts
tests/specs/StorageNode.spec.ts

- Export blockchain types (`BucketId`, `ClusterId`, ...) from. `ddc-client` package for easier access
- Align all bucket id usages to blockchain `BucketId` type (JS `bigint`)

Align bucketId type

---

package-lock.json
packages/ddc/package.json
packages/ddc/src/Cid.ts
tests/setup/environment/docker-compose.blockchain.ci.yml
tests/setup/environment/docker-compose.blockchain.yml
tests/specs/DdcApis.spec.ts
tests/specs/StorageNode.spec.ts

- Switch to [multiformats](https://www.npmjs.com/package/multiformats) to encode/decode CIDs
- Use only `base32` base to encode/decode CIDs, later we can add more decoding bases, just need to decide on the list
> Temporarily switched tests to use older version of blockchain nodes, since the last version introduces some braking changes which brakes tests. Since the latest BC version is not yet deployed to testnet we can temporarily fix tests to unblock S&T

Use multiformats base32 to encode/decode CIDs

---

packages/ddc-client/README.md
packages/ddc-client/src/DdcClient.ts
packages/ddc/src/FileApi/FileApi.ts
packages/ddc/src/Logger/createLogger.ts
packages/ddc/src/Logger/createLogger.web.ts
packages/ddc/src/Logger/types.ts
packages/ddc/src/Router/Router.ts
packages/ddc/src/StorageNode.ts
packages/file-storage/src/FileStorage.ts
tests/specs/DdcClient.spec.ts

- Refactor logger usages to re-use one logger instance
- Allow multiple log outputs (file and console)
- Add file output support

Allow multiple log outputs (console and file)

---

packages/ddc/src/FileApi/FileApi.ts
playground/src/Playground.tsx

In client stream gRPC requests the stream closes when the server (storage node) sends headers, so FileApi should also stop reading/streaming data in case it receives headers.

fix(ddc): Fix sending excessive messages to already closing upload stream

---

package-lock.json
packages/blockchain/src/Signer/UriSigner.ts
packages/blockchain/src/constants.ts
packages/blockchain/src/index.ts
packages/blockchain/src/utils/index.ts
packages/ddc-client/src/DdcClient.ts
packages/ddc-client/src/index.ts
packages/ddc/src/auth/AuthToken.ts
packages/ddc/src/index.ts
packages/ddc/src/nodes/NodeInterface.ts
packages/ddc/src/nodes/StorageNode.ts
packages/file-storage/src/FileStorage.ts
tests/setup/environment/docker-compose.ddc.yml
tests/specs/Auth.spec.ts

- Extend AuthToken API with methods related to delegation
- Allow passing the token to all operation methods
- Cover token delegation with tests
- Add high level method to DDCClient to grant access

feat: Extend auth token API with methods to delegate access

---

tests/helpers/blockchain.ts
tests/helpers/contract.ts
tests/setup/environment/blockchain.ts
tests/specs/Blockchain.spec.ts

Auth contract is optional and not needed in SDK tests. So removed it to fix the contract deployment errors and increase blockchain bootstrap time.

test: Remove Auth contract deployment from blockchain bootstrap script

---

package-lock.json
packages/ddc/package.json
packages/ddc/src/constants.ts
packages/ddc/src/routing/BaseStrategy.ts
packages/ddc/src/routing/BaseStrategy.web.ts
packages/ddc/src/routing/BlockchainStrategy.ts
packages/ddc/src/routing/NodeTypeStrategy.ts
packages/ddc/src/routing/PingStrategy.ts
packages/ddc/src/routing/RandomStrategy.ts
packages/ddc/src/routing/Router.ts
packages/ddc/src/routing/RoutingStrategy.ts
packages/ddc/src/routing/StaticStrategy.ts

Implement, ping based, routing strategy on top of existing, node type based, strategy. This is the first iteration of client side routing described in [this spec](https://www.notion.so/cere/Client-side-routing-f8b5b847be084bb5a4bb454ea726844a?pvs=4#c693c3bc37924d5db8735b52aa6c54e5).

feat(ddc): Add network latency based routing to select closest nodes to the client

---

package-lock.json
packages/cli/README.md
packages/cli/package.json
packages/cli/src/account.ts
packages/cli/src/cli.ts
packages/cli/src/constants.ts
packages/cli/src/createBucket.ts
packages/cli/src/createClient.ts
packages/cli/src/deposit.ts
packages/cli/src/index.ts
packages/cli/src/upload/index.ts
packages/cli/src/upload/uploadDir.ts
packages/cli/src/upload/uploadFile.ts
packages/cli/tsconfig.build.json

DDC CLI provides a flexible set of commands for developers to help setting up a DDC account, upload/download files and more. Check [README](https://github.com/Cerebellum-Network/cere-ddc-sdk-js/blob/feature/cli/packages/cli/README.md) from more info.
The command set is quite limited for now, only the ones needed for Drones AI demo project. But it will be improved later.

feat(cli): Introduce DDC command line interface

---

packages/blockchain/src/types.ts
tests/setup/environment/blockchain.ts
tests/setup/environment/docker-compose.blockchain.ci.yml
tests/setup/environment/docker-compose.blockchain.yml

- Replaced `--ws-*` node options with `--rpc-*` to fix blockchain startup on CI (still does not work on Mac)
- Added `isRemoved` property to bucket info type

tests: Fix blockchain bootstrap configuration

---

packages/blockchain/src/index.ts
packages/blockchain/src/utils/index.ts
packages/ddc/src/CnsApi/CnsApi.ts
packages/ddc/src/DagApi/DagApi.ts
packages/ddc/src/FileApi/FileApi.ts
packages/ddc/src/activity/createAck.ts
packages/ddc/src/activity/createActivityRequest.ts
packages/ddc/src/auth/AuthToken.ts
packages/ddc/src/auth/index.ts
packages/ddc/src/auth/sdkToken.ts
packages/ddc/src/nodes/StorageNode.ts
packages/ddc/src/routing/Router.ts
packages/ddc/src/signature/createSignature.ts
packages/ddc/src/signature/mapSignature.ts
tests/specs/StorageNode.spec.ts

Use token delegation mechanism to delegate access to internal SDK signer. The real signer needs to sign only the delegation and the rest is signed by internal SDK signer.
Note: This optimization currently not applied to use cases with external auth tokens

feat(ddc): Use internal SDK signers to reduce signature requests to web3 wallets

---

playground/src/Playground.tsx

DagNode data was incorrectly filled in Playground which led to eventual DagNode size limits error. Fixed it.

fix(playground): Fix Playground DagNode data overflow

---

.github/workflows/playground.yaml
.github/workflows/publish.yaml
.github/workflows/tests.yaml
packages/ddc/src/Piece.ts
packages/ddc/src/constants.ts
packages/ddc/src/index.ts
packages/ddc/src/nodes/BalancedNode.ts
packages/ddc/src/streams/createStream.ts
packages/file-storage/package.json
packages/file-storage/src/FileStorage.ts
packages/file-storage/src/constants.ts
packages/file-storage/src/constants.web.ts
packages/file-storage/src/index.ts
packages/file-storage/tsconfig.node.json
packages/file-storage/tsconfig.web.json
tests/helpers/streams.ts
tests/jest.config.ts
tests/specs/Auth.spec.ts
tests/specs/DdcClient.spec.ts
tests/specs/FileStorage.spec.ts

Note: Tests for this feature currently covers only happy pass - could not find an easy way to simulate failing storage node. Will try to find a way in another PR about re-triable download operations.

feat: Re-try piece store operation from buffered content

---

examples/cli/README.md
packages/cli/src/account.ts
packages/cli/src/cli.ts
packages/cli/src/createClient.ts

Add support for `nodes` config option to the CLI configuration files
Example of the configuration file:
```json
{
"signer": "gospel fee escape timber toilet crouch artist catalog salt icon bulb ivory",
"clusterId": "0x825c4b2352850de9986d9d28568db6f0c023a1e3",
"bucketId": "27327",
"nodes": [
{
"mode": "Full",
"grpcUrl": "grpc://128.140.103.37:9090",
"httpUrl": "https://storage-1.testnet.cere.network"
}
]
}
```
Upload file command example:
```sh
npx @cere-ddc-sdk/cli --config ./ddc.config.json upload ./2mb.jpg
```

feat(cli): Allow configuring DDC nodes list in CLI config

---

packages/cli/src/cli.ts
packages/cli/src/createClient.ts

Added new CLI options to override the default blockchain RPC URL:
```bash
npx cere-ddc --config ./ddc.config.json upload ./2mb.jpg --rpc wss://archive.testnet.cere.network/ws
```
or in the config file
```json
{
"blockchainRpc": "wss://archive.testnet.cere.network/ws",
"signer": "...",
"clusterId": "...",
"bucketId": "27496",
"nodes": [
{
"mode": "Full",
"grpcUrl": "grpc://ec2-52-27-0-63.us-west-2.compute.amazonaws.com:8080",
"httpUrl": "http://ec2-52-27-0-63.us-west-2.compute.amazonaws.com:8080"
}
]
}
```

feat(cli): Add CLI option to override default blockchain RPC URL

---

packages/blockchain/docs/README.md
packages/blockchain/docs/classes/CereWalletSigner.md
packages/blockchain/docs/classes/DDCClustersPallet.md
packages/blockchain/docs/classes/JsonSigner.md
packages/blockchain/docs/classes/KeyringSigner.md
packages/blockchain/docs/classes/Signer.md
packages/blockchain/docs/classes/Web3Signer.md
packages/ddc-client/docs/README.md
packages/ddc-client/docs/classes/DdcClient.md
packages/ddc-client/docs/classes/JsonSigner.md
packages/ddc-client/docs/classes/KeyringSigner.md
packages/ddc-client/docs/classes/Signer.md
packages/ddc-client/docs/classes/UriSigner.md
packages/ddc/docs/README.md
packages/ddc/docs/classes/JsonSigner.md
packages/ddc/docs/classes/KeyringSigner.md
packages/ddc/docs/classes/Signer.md
packages/ddc/docs/classes/UriSigner.md
packages/file-storage/docs/classes/Signer.md
packages/file-storage/docs/classes/UriSigner.md

Update documentation of recently added changes

docs: Update blockchain signers documentation

---

packages/ddc/src/nodes/BalancedNode.ts
packages/ddc/src/routing/NodeTypeStrategy.ts
packages/ddc/src/routing/PingStrategy.ts
packages/file-storage/src/FileStorage.ts

- Enable exponential backoff re-try strategy by default starting from 50ms timeout
- Fix ping based routing node selection - it was sometimes selecting not pinged node
- Allow configuring re-try policy

feature: Improve re-try logic with exponential backoff strategy

---

packages/cli/src/cli.ts
packages/cli/src/createClient.ts
packages/cli/src/download/downloadDir.ts
packages/cli/src/download/downloadFile.ts
packages/cli/src/upload/index.ts
packages/cli/src/upload/uploadDir.ts
packages/cli/src/upload/uploadFile.ts
packages/ddc-client/src/index.ts
packages/ddc/src/CnsApi/CnsApi.ts
packages/ddc/src/DagApi/DagApi.ts
packages/ddc/src/FileApi/FileApi.ts
packages/ddc/src/activity/createCorrelationId.ts
packages/ddc/src/activity/createRpcMeta.ts
packages/ddc/src/activity/index.ts
packages/ddc/src/auth/createRpcMeta.ts
packages/ddc/src/index.ts
packages/ddc/src/nodes/BalancedNode.ts
packages/ddc/src/nodes/NodeInterface.ts
packages/ddc/src/nodes/StorageNode.ts
packages/ddc/src/routing/Router.ts
packages/ddc/src/transports/RpcTransport.ts
packages/file-storage/src/index.ts
tests/helpers/ddc.ts
tests/specs/ActivityCapture.spec.ts

- Add new optional option to all operation methods: `correlationId`
- Pass this new option to gRPC meta by name `CorrelationID`
- If not provided - generate a random string in `uuid` format
- Add the support to CLI
- Cover with tests

feature: Add support for correlationId to group several requests

---

.github/workflows/playground.yaml
packages/ddc/src/auth/AuthToken.ts
packages/ddc/src/nodes/StorageNode.ts
tests/specs/Auth.spec.ts

The SDK was always signing a provided access token event if it is already signed. It led to problems with signed, not delegated tokens shared between  users. The tokens signature was updated making the tokens invalid.
After this fix, if the token is already properly signed the SDK will not sign it again.
Related bug report:
https://www.notion.so/cere/One-level-access-tokens-72b586e30b1744768ed480689043ff45?pvs=4

fix(ddc): Do not sign an access token if already signed properly

---

packages/ddc/src/CnsApi/CnsApi.ts
packages/ddc/src/DagNode.ts
packages/ddc/src/nodes/NodeInterface.ts
packages/ddc/src/nodes/StorageNode.ts
tests/specs/CacheControl.spec.ts

Added a new option to all `read` operation of the SDK called `cacheControl`. Currently it allows passing only fixed value `no-cache` - to disable CNS cache completely, but later it can be extended if needed.

feature: Add CNS Record cache control option

---

package-lock.json
packages/blockchain/package.json
packages/blockchain/src/Blockchain.ts
packages/blockchain/src/Signer/CereWalletSigner.ts
packages/ddc-client/src/DdcClient.ts
playground/package.json

Refactored Cere Wallet signer to not use `inject` package from Polkadot.

fix: Cere Wallet signer not triggering 3rd party extensions consent

---

packages/blockchain/src/Signer/CereWalletSigner.ts
packages/ddc-client/src/DdcClient.ts

Sometimes Cere Wallet signer account is not defined right after connecting the wallet. It happens due to async nature of wallet events over `postMessage` and it can happen that `inited` event appears before `update-accounts` event. Fixed it by manually fetching addresses after connect.

fix: Make sure Cere Wallet address always stays in sync

---

packages/ddc/src/auth/sdkToken.ts
packages/ddc/src/routing/Router.ts

Cere Wallet signer address can be changed without re-initialization of the SDK. We need to rebuild the internal SDK token for new accounts of the signer.

fix: Update SDK token if signer address changed

---

packages/blockchain/src/Blockchain.ts
packages/blockchain/src/DDCCustomersPallet.ts

`BucketCreated` event has been updated on `Devnet` - new fields added in front of old ones (a braking change). have to change the event decoding algo to not rely on args order

fix: Properly get bucketId from BucketCreated event

---

packages/ddc/src/routing/BlockchainStrategy.ts
packages/ddc/src/routing/Router.ts
packages/ddc/src/signature/createSignature.ts

- Fix an issue with Auth tokens signing when it throws an error if the signer is not ready
- Added an explicit error about empty node list in a cluster

fix(ddc): Auth token sign method waits the signer to become ready

---

packages/ddc-client/src/DdcClient.ts
packages/ddc-client/src/index.ts
packages/ddc/src/logger/types.ts
packages/ddc/src/nodes/BalancedNode.ts
packages/ddc/src/nodes/NodeError.ts
packages/ddc/src/nodes/NodeInterface.ts
packages/ddc/src/nodes/StorageNode.ts
packages/ddc/src/nodes/index.ts
packages/ddc/src/routing/Router.ts
packages/file-storage/src/FileStorage.ts
tests/helpers/ddc.ts
tests/specs/Errors.spec.ts

- Extend storage node RPC errors with `correlationId` and `nodeId` (gRPC endpoint)
- Make client router errors more informative instead of just `No nodes found...`

feature: Extend node operation errors with correlation ID and node URL

---

.github/workflows/publish.yaml
.github/workflows/tests.yaml
examples/node/1-create-bucket/index.ts
packages/blockchain/docs/classes/DDCCustomersPallet.md
packages/blockchain/src/DDCCustomersPallet.ts
packages/cli/src/account.ts
packages/cli/src/cli.ts
packages/cli/src/deposit.ts
packages/ddc-client/docs/classes/DdcClient.md
packages/ddc-client/src/DdcClient.ts
playground/src/Playground.tsx
tests/setup/environment/blockchain.ts
tests/setup/environment/docker-compose.blockchain.ci.yml
tests/setup/environment/docker-compose.blockchain.yml
tests/setup/environment/docker-compose.ddc.yml
tests/specs/DdcClient.spec.ts
tests/specs/Errors.spec.ts

- Migrated from ledger to clusterLedger in ddcCustomers pallet
- Updated deposit, depositExtra, unlockDeposit, and withdrawUnlockedDeposit methods to support clusterId
- Added new methods: depositFor, depositBalanceFor, getStackingInfoLegacy
- Updated CLI commands: deposit and account
- Updated tests and examples

Support breaking changes in DDC SDK
