.github/workflows/release.yaml
packages/content-addressable-storage/src/ContentAddressableStorage.ts
packages/content-addressable-storage/src/lib/gas-counter.ts
packages/ddc-client/src/DdcClient.ts
packages/ddc-client/src/model/File.ts
packages/file-storage/src/browser.ts
packages/file-storage/src/index.ts
packages/file-storage/src/types.ts
packages/file-storage/src/utils.ts
packages/key-value-storage/src/KeyValueStorage.ts
scripts/release-artifacts.js
tests/ContentAddressableStorage.spec.ts

feat: Improve ack

---

packages/content-addressable-storage/README.md
packages/content-addressable-storage/src/ContentAddressableStorage.ts
packages/content-addressable-storage/src/ca-create-options.ts
packages/content-addressable-storage/src/index.ts
packages/content-addressable-storage/src/lib/init-default-options.ts
packages/ddc-client/src/DdcClient.interface.ts
packages/ddc-client/src/DdcClient.ts
packages/ddc-client/src/browser.ts
packages/ddc-client/src/index.ts
packages/ddc-client/src/lib/init-default-client-options.ts
packages/ddc-client/src/options/ClientOptions.ts
packages/ddc-client/src/options/ReadOptions.ts
packages/ddc-client/src/options/StoreOptions.ts
packages/file-storage/src/browser.ts
packages/file-storage/src/core/CoreFileStorage.ts
packages/file-storage/src/index.ts
packages/file-storage/src/types.ts
packages/key-value-storage/src/KeyValueStorage.ts
tests/ContentAddressableStorage.spec.ts
tests/DdcClient.spec.ts
tests/FileStorage.spec.ts
tests/KeyValueStorage.spec.ts
tests/save-with-empty-nonce.ts

Move session argument into options

---

CHANGELOG.md
package-lock.json
package.json
packages/content-addressable-storage/package.json
packages/core/package.json
packages/ddc-client/package.json
packages/file-storage/package.json
packages/key-value-storage/package.json
packages/proto/package.json
packages/smart-contract/package.json
packages/smart-contract/src/options/SmartContractOptions.ts

Update Smart Contract addresses for all environments

---

.github/workflows/publish.yaml
CHANGELOG.md
packages/content-addressable-storage/package.json
packages/core/package.json
packages/ddc-client/package.json
packages/file-storage/package.json
packages/key-value-storage/package.json
packages/proto/package.json
packages/smart-contract/package.json
packages/smart-contract/src/SmartContractBase.ts
tests/SmartContract.spec.ts

- Fixed RPC errors handling which occurs before the transaction is added to the pool
- Added tests to cover these error cases
- Fixed publish flow

Fix RPC error handling and add the errors tests

---

lerna.json
package-lock.json
packages/content-addressable-storage/package.json
packages/core/package.json
packages/ddc-client/package.json
packages/file-storage/package.json
packages/key-value-storage/package.json
packages/proto/package.json
packages/smart-contract/README.md
packages/smart-contract/package.json
packages/smart-contract/src/SmartContract.ts
tests/SmartContract.spec.ts

added frevokeTrustedManagerPermission method

feat: revokeTrustedManagerPermission method for sc

---

packages/content-addressable-storage/src/ContentAddressableStorage.ts
packages/content-addressable-storage/src/StorageOptions.ts
packages/content-addressable-storage/src/constants.ts
packages/content-addressable-storage/src/index.ts
packages/content-addressable-storage/src/lib/init-default-options.ts
packages/ddc-client/src/lib/init-default-client-options.ts
packages/ddc-client/src/options/ClientOptions.ts
tests/FileStorage.spec.ts
tests/Routing.spec.ts
tests/SmartContract.spec.ts
tests/setup/collectionPoint/index.ts
tests/setup/routing/index.ts

Enable DAC v3 by default, using Router and Collection Point services from `dev` environment

Enable DAC v3 approach by default (devnet only)

---

lerna.json
package-lock.json
packages/content-addressable-storage/package.json
packages/core/package.json
packages/ddc-client/package.json
packages/file-storage/package.json
packages/key-value-storage/package.json
packages/proto/package.json
packages/smart-contract/README.md
packages/smart-contract/package.json
packages/smart-contract/src/SmartContract.ts
packages/smart-contract/src/types/contractTypes.ts
tests/SmartContract.spec.ts

feat: hasPermission method

---

package.json
packages/ddc/protos/file_api.proto
packages/ddc/src/FileApi/FileApi.ts
packages/ddc/src/StorageNode.ts
packages/ddc/src/constants.ts
packages/ddc/src/grpc/file_api.client.ts
packages/ddc/src/grpc/file_api.ts
tests/setup/environment/docker-compose.ddc.yml
tests/v2/DdcApis.spec.ts
tests/v2/SmartContract.spec.ts

- Change file read request from `unary` to `client stream`

Update file read from unary to stream request

---

packages/ddc-client/src/DdcClient.ts
packages/ddc-client/src/DdcUri.ts
packages/ddc/LICENSE
packages/ddc/package.json
packages/file-storage/src/FileStorage.ts
packages/smart-contract/src/options/SmartContractOptions.ts
tests/v2/DdcClient.spec.ts

- Added `module` export to `ddc` package
- Added static `create` method to file storage to align it to DdcClient in terms of creation API
- `CNS` name is now available on `DdcUri` instance returned by `store` method

SDK fixes and adjustments

---

jest.config.ts
package-lock.json
package.json
packages/blockchain/src/Blockchain.ts
packages/blockchain/src/Signer/Signer.ts
packages/blockchain/src/Signer/UriSigner.ts
packages/blockchain/src/Signer/index.ts
packages/blockchain/src/index.ts
packages/blockchain/tsconfig.build.json
packages/ddc-client/src/DdcClient.ts
packages/ddc-client/src/DdcUri.ts
packages/ddc-client/src/index.ts
packages/ddc-client/tsconfig.build.json
packages/ddc/package.json
packages/ddc/src/CnsRecord.ts
packages/ddc/src/Router/Router.ts
packages/ddc/src/StorageNode.ts
packages/ddc/src/index.ts
packages/ddc/src/presets.ts
packages/ddc/tsconfig.node.json
packages/file-storage/package.json
packages/file-storage/src/File.ts
packages/file-storage/src/FileStorage.ts
packages/file-storage/src/index.ts
packages/file-storage/tsconfig.build.json
playground/tsconfig.json
tests/specs/Blockchain.spec.ts
tsconfig.build.json
tsconfig.json

- Moved `Signer` implementation to `blockchain` package to keep all blockchain related  deps in one place
- Added `CI` test project to run tests on built version of packages
- Added `Dev` test project to run tests on source code
- Added config presets support to `file-storage` package to align it with `ddc-client` package

Refactor packages dependencies and add CI tests

---

package-lock.json
packages/ddc-client/src/DdcClient.ts
packages/ddc/package.json
packages/ddc/src/DagNode.ts
packages/ddc/src/StorageNode.ts
tests/specs/DdcApis.spec.ts
tests/specs/DdcClient.spec.ts
tests/specs/StorageNode.spec.ts

Added `path` param to all DagNode methods and covered with tests.

Add `path` queries to DagNode related methods

---

.gitignore
CHANGELOG.md
README.md
lerna.json
nx.json
package-lock.json
package.json
packages/ddc-client/src/DdcClient.ts
packages/ddc/src/StorageNode.ts
playground/package.json
tests/jest.config.ts
tests/package.json
tests/tsconfig.json
tsconfig.build.json

Use `NX` to configure tasks pipelines.
- Always pre-build packages before tests
- Always pre-build packages before running playground
- Update Lerna to v8
- Update documentation about Playground

Always pre-build packages before tests

---

packages/ddc/src/FileApi/FileApi.ts
packages/ddc/src/Piece.ts
packages/ddc/src/streams/createStream.ts
packages/file-storage/src/FileStorage.ts
tests/specs/DdcApis.spec.ts
tests/specs/StorageNode.spec.ts

- Add raw piece size detection (from static content or from provided size in case of a stream)
- Send ActivityRequest to putRawPiece call meta

Add ActivityRequest to putRawPiece meta

---

package.json
packages/ddc/src/FileApi/FileApi.ts
packages/ddc/src/Piece.ts
packages/ddc/src/Router/BaseRouter.ts
packages/ddc/src/Router/Router.web.ts
packages/ddc/src/Router/index.ts
packages/ddc/src/StorageNode.ts
packages/ddc/src/presets.ts
packages/ddc/src/transports/RpcTransport.ts
packages/ddc/src/transports/WebsocketTransport.ts
playground/src/Playground.tsx
tests/jest.config.ts

- Add `ssl` flag to node params
- Add 1 node with ssl support to DEVNET preset

Filter nodes with ssl support for web

---

packages/ddc/package.json
packages/ddc/src/FileApi/FileApi.ts
packages/ddc/src/Piece.ts
packages/ddc/src/index.ts
packages/ddc/src/streams/consumers.ts
packages/ddc/src/streams/consumers.web.ts
packages/ddc/src/streams/createStream.ts
packages/ddc/src/streams/index.ts
packages/ddc/src/streams/splitStream.ts
packages/ddc/src/streams/streams.ts
packages/ddc/src/streams/streams.web.ts
packages/eslint-config/index.js

Use native whatwg streams in browser Instead of polyfill

Use native streams in browser

---

nx.json
package-lock.json
packages/ddc/src/index.ts
playground/package.json
playground/tsconfig.json
playground/vite.config.ts

Simplify the SDK development and experiments in playground by building the app directly from source code

Build playground app from source

---

package-lock.json
packages/ddc-client/src/DdcClient.ts
packages/ddc/package.json
packages/ddc/src/FileApi/FileApi.ts
packages/ddc/src/Logger/createLogger.ts
packages/ddc/src/Logger/createLogger.web.ts
packages/ddc/src/Logger/index.ts
packages/ddc/src/Logger/types.ts
packages/ddc/src/Router/BaseRouter.ts
packages/ddc/src/StorageNode.ts
packages/ddc/src/index.ts
packages/file-storage/src/FileStorage.ts
playground/src/Playground.tsx
playground/tsconfig.json
tests/specs/DdcClient.spec.ts

- Add NodeJs logger (pino)
- Add browser logger (console)

Add logging for most important operations

---

package-lock.json
packages/ddc/src/DagNode.ts
playground/package.json
playground/src/Playground.tsx

- Added links to file downloads
- Add support for long file names (DAG API + CNS API)
- Fixed several issues

Playground improvements and fixes

---

packages/ddc/src/Logger/createLogger.ts
packages/ddc/src/Logger/createLogger.web.ts
packages/ddc/src/Logger/types.ts

Allow specify log formats for both console and file outputs

Allow specifying log format

---

packages/blockchain/src/DDCStakingPallet.ts

Cluster management needs this API

List stakes

---

packages/blockchain/src/Blockchain.ts

Cluster management needs this API

Account balance

---

packages/blockchain/src/Blockchain.ts
packages/ddc-client/src/DdcClient.ts
packages/file-storage/src/FileStorage.ts
tests/setup/environment/blockchain.ts
tests/specs/Blockchain.spec.ts

- allow blockchain reads without specifying account
- provide (optional) signer for blockchain writes

Blockchain writes signer

---

packages/blockchain/src/Blockchain.ts
packages/blockchain/src/DDCClustersPallet.ts
packages/blockchain/src/DDCCustomersPallet.ts
playground/package.json
playground/src/Playground.tsx

Allow selecting/creating buckets using playground application

Add select bucket step to playground

---

packages/blockchain/src/DDCClustersPallet.ts
packages/blockchain/src/DDCCustomersPallet.ts
packages/blockchain/src/DDCNodesPallet.ts
packages/blockchain/src/DDCStakingPallet.ts
packages/blockchain/src/types.ts
packages/ddc-client/src/DdcClient.ts
tests/setup/environment/blockchain.ts
tests/specs/Blockchain.spec.ts
tests/specs/DdcClient.spec.ts

- Add storage node `mode` param
- Remove mentions of CDN nodes
- Add bucket `isPublic` param

chore!: Add storage node mode and `isPublic` bucket property

---

packages/blockchain/src/DDCNodesPallet.ts
packages/blockchain/src/types.ts
packages/ddc/src/Router/BlockchainStrategy.ts
tests/specs/Blockchain.spec.ts

- Add new props to `StorageNodeParams`
- Update router to use these new props

feat(blockchain): Add support for new node props - `domain` and `ssl`

---

packages/ddc/src/presets.ts
playground/src/Playground.tsx

- Switch `TESTNET` preset to on-chain network topology
- Temporarily keep static presets with deprecation tag and TODO

feat(ddc): Update TESTNET preset to use on-chain network topology

---

package-lock.json
packages/ddc/src/FileApi/FileApi.ts
packages/ddc/src/streams/splitStream.ts
packages/file-storage/src/FileStorage.ts
playground/src/Playground.tsx
tests/helpers/ddc.ts
tests/setup/environment/blockchain.ts
tests/specs/Auth.spec.ts
tests/specs/DdcClient.spec.ts
tests/specs/FileStorage.spec.ts
tests/specs/StorageNode.spec.ts

- Fix file access error handling
- Add file access tests

fix(ddc): Properly handle file access errors

---

packages/ddc/src/presets.ts
tests/setup/environment/docker-compose.blockchain.ci.yml
tests/setup/environment/docker-compose.blockchain.yml

Switch to devnet blockchain in DEVNET preset and tests

chore: Switch to latest DEVNET blockchain in tests and playground

---

packages/blockchain/src/Blockchain.ts
tests/specs/Blockchain.spec.ts

Required for cluster management

feat(blockchain): Add method to get current block number

---

.github/workflows/tests.yaml
tests/setup/environment/docker-compose.blockchain.ci.yml
tests/setup/environment/docker-compose.blockchain.yml

- Run tests on merge to `main` branch
- Run tests on schedule
- Use `dev-latest` blockchain image in tests

test: Run tests on merge to main branch and on schedule

---

packages/ddc/src/transports/WebsocketTransport.ts

WebSocket transport did not handle gRPC headers error in accordance to specification. It should reject in case of not OK status code, but it did not.

fix(ddc): Properly handle gRPC headers error in WebSocket transport

---

packages/ddc-client/README.md
packages/ddc-client/src/DdcClient.ts

docs(ddc-client): Update ddc-client package documentation

---

packages/ddc/src/presets.ts
playground/src/Playground.tsx

Use real MAINNET blockchain endpoint instead of QANET in MAINNET SDK preset

fix(ddc): Use proper MAINNET preset blockchain endpoint

---

package-lock.json
packages/blockchain/package.json

Update all `@polkadot/*` packages to latest version in the SDK `blockchain` package.

chore(blockchain): Update all blockchain package dependencies to the latest versions

---

package-lock.json
packages/blockchain/package.json
packages/blockchain/src/Blockchain.ts
packages/blockchain/src/DDCCustomersPallet.ts
packages/blockchain/src/Signer/CereWalletSigner.node.ts
packages/blockchain/src/Signer/CereWalletSigner.ts
packages/blockchain/src/Signer/Web3Signer.ts
packages/blockchain/src/Signer/index.ts
packages/blockchain/src/index.ts
packages/ddc-client/src/DdcClient.ts
playground/package.json
playground/src/Playground.tsx
playground/src/constants.ts
tests/setup/environment/blockchain.ts
tests/specs/DdcClient.spec.ts

- Add DDC Client methods to deposit balance
- Add Cere Wallet signer implementation
- Update playground to support Cere Wallet integration

feat: Add Cere Wallet support

---

packages/blockchain/src/Signer/Web3Signer.ts

Since we are going to auto-sign messages needed for DDC to operate (ACKs, Activity Requests, CNS records, etc...), we need to make sure that this flow will not be used to sign real transactions.

Protect DDC Web3Signer from signing real transactions

---

package-lock.json
packages/cli/LICENSE
packages/cli/package.json
packages/cli/src/account.ts
packages/cli/src/cli.ts
packages/cli/src/download/downloadDir.ts
packages/cli/src/download/downloadFile.ts
packages/cli/src/download/index.ts
packages/cli/src/upload/uploadDir.ts
packages/ddc-client/src/DdcClient.ts
packages/ddc/src/Cid.ts

Added new CLI commands:
- `download` - downloads file or directory by CID or cnsName
- `account` - returns account information or generate new if `--random` option provided

feat(cli): Add commands to download files and directories

---

package-lock.json
packages/blockchain/package.json
packages/ddc-client/src/DdcClient.ts
packages/ddc/src/CnsApi/CnsApi.ts
packages/ddc/src/DagApi/DagApi.ts
packages/ddc/src/FileApi/FileApi.ts
packages/ddc/src/constants.ts
packages/ddc/src/logger/bindErrorLogger.ts
packages/ddc/src/logger/createLogger.ts
packages/ddc/src/nodes/BalancedNode.ts
packages/ddc/src/nodes/StorageNode.ts
packages/ddc/src/routing/Router.ts
packages/ddc/src/streams/createStream.ts
packages/file-storage/src/FileStorage.ts
playground/package.json
playground/src/Playground.tsx
playground/src/vite-env.d.ts
playground/vite.config.ts
tests/helpers/ddc.ts
tests/helpers/streams.ts
tests/jest.config.ts
tests/setup/environment/docker-compose.ddc.yml
tests/specs/DdcApis.spec.ts
tests/specs/FileStorage.spec.ts

- Send ACKs without `await`
- Fix logging issues
- Update Playground app to not fetch all buckets from the blockchain

feat: Add async acknowledgements support

---

packages/blockchain/src/DDCClustersPallet.ts
packages/blockchain/src/types.ts
tests/specs/Blockchain.spec.ts

- Updated ClusterProps type adding new properties
- Added default values to the new props to not introduce a braking change

feat(blockchain): Add support for new cluster properties

---

examples/cli/6PxrvjkVJFrQs6Tqdeov1GcJkS5rpzuM3NYGhX8KQErv49V2.json
examples/cli/README.md
packages/blockchain/src/Signer/JsonSigner.ts
packages/blockchain/src/Signer/KeyringSigner.ts
packages/blockchain/src/Signer/Signer.ts
packages/blockchain/src/Signer/UriSigner.ts
packages/blockchain/src/Signer/Web3Signer.ts
packages/blockchain/src/Signer/index.ts
packages/cli/src/account.ts
packages/cli/src/cli.ts
packages/cli/src/createClient.ts
packages/ddc-client/src/index.ts
packages/ddc/src/index.ts

- Added new type of signer: JsonSigner
- Added the new signer support to CLI

feat: Add support of signers created from a JSON backup file

---

tests/specs/Blockchain.spec.ts

Jest specs are run in parallel which can sometimes lead to account nonce collision if the same account used in multiple specs. Fixed the flaky tests by creating a dedicated account for blockchain spec.

chore: Use a dedicated account in blockchain tests to resolve flaky tests

---

packages/ddc/src/activity/createRpcMeta.ts
tests/specs/ActivityCapture.spec.ts

Fix for incorrect Correlation ID meta key

fix(ddc): Update correlation id gRPC meta key

---

packages/cli/src/cli.ts
packages/cli/src/token.ts

- Fix an issue related to bucket access CLI option
- Make token expiration time CLI option in seconds instead of milliseconds

fix(cli): Make it possible to create public buckets using CLI
